### ISSUE TITLE
Can not find file dti_trilin/bin/tensors.nii.gz

### ISSUE THREAD

**Issue by soichih** [brain-life/app-tractclassification#3]
I started getting following error message recently.

```

{Error using dtiLoadTensorsFromNifti (line 30)
Can not find file
../598cd4efb7e0480a04f9cde2/5987bf13e5380447a5202592/dti_trilin/bin/tensors.nii.gz


Error in dtiLoadDt6 (line 67)
    [dt.dt6, dt.xformToAcpc, dt.mmPerVoxel] =
    dtiLoadTensorsFromNifti(dt6Struct.files.tensors);

Error in AFQ_SegmentFiberGroups (line 143)
    dt = dtiLoadDt6(dt6File);


Error in main (line 41)
[fg_classified,~,classification]= AFQ_SegmentFiberGroups(config.dt6, fg, [],
[], config.useinterhemisphericsplit);
} 

```

I am using app-dtiinit output, and as far as I know, it doesn't generate bin/tensor.nii.gz (but app-testgradientflip does!) 

I was using following configuration

```
 "useinterhemisphericsplit": false,
  "remove_zero_weighted_fibers": "before",
  "fe": "../598cd4efb7e0480a04f9cde2/598c5e7cb6f242245e2056e6/output_fe.mat",
  "dt6": "../598cd4efb7e0480a04f9cde2/5987bf13e5380447a5202592/dti_trilin/dt6.mat",
```

**Comment by kitchell** [comment]
ditinit should be creating the tensors.nii.gz file. the test gradient flip app is just running dtiinit for all flipped directions. I just checked the dtiinit outputs I have on brainlife (ran on the 30th) and tensors.nii.gz is in the bin folder.

**Comment by kitchell** [comment]
@soichih was this solved?

**Comment by soichih** [comment]
Yes, the issue was caused by missing directory on the dtiinit_output datatype. Closing this ticket.
